version: '3'
services:
  goexperiment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goexperiment
    ports:
      - "5000:5000"
    network_mode: "host"
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    network_mode: "host"